name: "Main Workflow"
on:
  push:
    tags:
      - "v*"
    branches:
      - master

jobs:
  build-docker:
     name: "Build image and push"
     runs-on: ubuntu-20.04

     steps:
     - name: Checkout
       uses: actions/checkout@v2
    
     - name: Regular
       run : echo TAG="HELLO" >> $GITHUB_ENV
       if: "!startsWith(github.ref, 'refs/tags/v')"

     - name: Print out test VAR
       run: echo $TAG
       if: "!startsWith(github.ref, 'refs/tags/v')"

     - name: Get TAG
       id: get_tag
       run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
       if: startsWith(github.ref, 'refs/tags/v')

     - uses: mr-smithers-excellent/docker-build-push@v5
       name: Build & push Docker image
       if: startsWith(github.ref, 'refs/tags/v')
       with:
         image: mpetrovic992/time-app
         tags: ${{ steps.get_tag.outputs.VERSION }}, latest
         registry: docker.io
         dockerfile: Dockerfile
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
